spring:
  datasource:
    url: jdbc:mysql://192.168.127.66:3306/atcrowdfunding
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  